# Generated by Django 2.1.5 on 2019-03-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device_site',
            options={},
        ),
    ]
