# Generated by Django 2.1.4 on 2019-04-08 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20190320_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_data',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('type_1', models.FloatField(null=True)),
                ('type_2', models.FloatField(null=True)),
                ('type_3', models.FloatField(null=True)),
                ('type_4', models.FloatField(null=True)),
                ('type_5', models.FloatField(null=True)),
                ('type_6', models.FloatField(null=True)),
                ('type_7', models.FloatField(null=True)),
                ('type_8', models.FloatField(null=True)),
                ('type_9', models.FloatField(null=True)),
                ('type_10', models.FloatField(null=True)),
                ('type_11', models.FloatField(null=True)),
                ('type_12', models.FloatField(null=True)),
                ('type_13', models.FloatField(null=True)),
                ('type_14', models.FloatField(null=True)),
                ('type_15', models.FloatField(null=True)),
                ('type_16', models.FloatField(null=True)),
                ('type_17', models.FloatField(null=True)),
                ('type_18', models.FloatField(null=True)),
                ('type_19', models.FloatField(null=True)),
                ('type_20', models.FloatField(null=True)),
                ('type_21', models.FloatField(null=True)),
                ('type_22', models.FloatField(null=True)),
                ('type_23', models.FloatField(null=True)),
                ('type_24', models.FloatField(null=True)),
                ('type_25', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'SensorData_Table',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='device_site',
            options={'managed': False},
        ),
    ]
