# Generated by Django 2.1.4 on 2019-04-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_auto_20190408_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor_data',
            options={'managed': True},
        ),
    ]
