# Generated by Django 2.1.4 on 2019-04-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_sensor_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor_data',
        ),
    ]
