# Generated by Django 2.1.4 on 2019-04-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0007_delete_sensor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_1', models.FloatField(default='0')),
                ('type_2', models.FloatField(default='0')),
                ('type_3', models.FloatField(default='0')),
                ('type_4', models.FloatField(default='0')),
                ('type_5', models.FloatField(default='0')),
                ('type_6', models.FloatField(default='0')),
                ('type_7', models.FloatField(default='0')),
                ('type_8', models.FloatField(default='0')),
                ('type_9', models.FloatField(default='0')),
                ('type_10', models.FloatField(default='0')),
                ('type_11', models.FloatField(default='0')),
                ('type_12', models.FloatField(default='0')),
                ('type_13', models.FloatField(default='0')),
                ('type_14', models.FloatField(default='0')),
                ('type_15', models.FloatField(default='0')),
                ('type_16', models.FloatField(default='0')),
                ('type_17', models.FloatField(default='0')),
                ('type_18', models.FloatField(default='0')),
                ('type_19', models.FloatField(default='0')),
                ('type_20', models.FloatField(default='0')),
                ('type_21', models.FloatField(default='0')),
                ('type_22', models.FloatField(default='0')),
                ('type_23', models.FloatField(default='0')),
                ('type_24', models.FloatField(default='0')),
                ('type_25', models.FloatField(default='0')),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'SensorData_Table',
            },
        ),
    ]
